version: "3.7"
services:
  authentication_module:
      container_name: "farewell_authentication_module"
      image: "farewell/authentication_module:latest"
      ports:
        - 7000:8080
      depends_on:
        - db
  reservation_module:
    container_name: "farewell_reservation_module"
    image: "farewell/reservation_module:latest"
    ports:
      - 8080:8080
    depends_on:
      - db
  analytical_module:
    container_name: "farewell_analytical_module"
    image: "farewell/analytical_module:latest"
    ports:
      - 8081:8081
    depends_on:
      - db
      - reservation_module
  db:
    container_name: "farewell_db"
    image: "postgres:11.7"
    volumes:
#      - ./db_init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./postgres_data:/var/lib/postgresql/data
#      - ./db_init_scripts/init-user-db-old.sh:/docker-entrypoint-initdb.d/init-user-db-old.sh
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=reservations_db,analytical_db,app_test,authentication_db
    ports:
      - 5432:5432